language: node_js
env:
  - CODECLIMATE_REPO_TOKEN=c4c0a7c1145a59087bdb9ec386ba6a7b531ff07bb016b3f6c6afd9ad5a28b79d
node_js:
  - '6.2'
  - '5.1'
  - '4.2'
  - '0.12'
after_script:
  - npm test --coverage
  - codeclimate-test-reporter < coverage/lcov.info
