branches:
  only:
    - master
    - develop
language: node_js
sudo: required
addons:
  code_climate:
node_js:
  - '0.12'
  - '0.11'
  - '0.10'
after_script:
  - npm test --coverage
  - codeclimate-test-reporter < coverage/lcov.info
